(function(){'use strict';var r,t="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},u="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this;function v(){v=function(){};u.Symbol||(u.Symbol=aa)}var ba=0;function aa(a){return"jscomp_symbol_"+(a||"")+ba++}
function w(){v();var a=u.Symbol.iterator;a||(a=u.Symbol.iterator=u.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&t(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(this)}});w=function(){}}function ca(a){var b=0;return fa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function fa(a){w();a={next:a};a[u.Symbol.iterator]=function(){return this};return a}
function ga(a,b){if(b){var c=u;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&t(c,a,{configurable:!0,writable:!0,value:b})}}function x(a){w();var b=a[Symbol.iterator];return b?b.call(a):ca(a)}function z(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
ga("WeakMap",function(a){function b(a){this.S=(h+=Math.random()+1).toString();if(a){v();w();a=x(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}}function c(a){z(a,e)||t(a,e,{value:{}})}function d(a){var b=Object[a];b&&(Object[a]=function(a){c(a);return b(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d.delete(b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(m){return!1}}())return a;
var e="$jscomp_hidden_"+Math.random().toString().substring(2);d("freeze");d("preventExtensions");d("seal");var h=0;b.prototype.set=function(a,b){c(a);if(!z(a,e))throw Error("WeakMap key fail: "+a);a[e][this.S]=b;return this};b.prototype.get=function(a){return z(a,e)?a[e][this.S]:void 0};b.prototype.has=function(a){return z(a,e)&&z(a[e],this.S)};b.prototype.delete=function(a){return z(a,e)&&z(a[e],this.S)?delete a[e][this.S]:!1};return b});
ga("Map",function(a){function b(){var a={};return a.C=a.next=a.head=a}function c(a,b){var c=a.B;return fa(function(){if(c){for(;c.head!=a.B;)c=c.C;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})}function d(a,b){var c;c=b&&typeof b;"object"==c||"function"==c?h.has(b)?c=h.get(b):(c=""+ ++f,h.set(b,c)):c="p_"+b;var d=a.R[c];if(d&&z(a.R,c))for(a=0;a<d.length;a++){var e=d[a];if(b!==b&&e.key!==e.key||b===e.key)return{id:c,list:d,index:a,j:e}}return{id:c,list:d,
index:-1,j:void 0}}function e(a){this.R={};this.B=b();this.size=0;if(a){a=x(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(x([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?
!1:!0}catch(n){return!1}}())return a;v();w();var h=new WeakMap;e.prototype.set=function(a,b){var c=d(this,a);c.list||(c.list=this.R[c.id]=[]);c.j?c.j.value=b:(c.j={next:this.B,C:this.B.C,head:this.B,key:a,value:b},c.list.push(c.j),this.B.C.next=c.j,this.B.C=c.j,this.size++);return this};e.prototype.delete=function(a){a=d(this,a);return a.j&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.R[a.id],a.j.C.next=a.j.next,a.j.next.C=a.j.C,a.j.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.R=
{};this.B=this.B.C=b();this.size=0};e.prototype.has=function(a){return!!d(this,a).j};e.prototype.get=function(a){return(a=d(this,a).j)&&a.value};e.prototype.entries=function(){return c(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return c(this,function(a){return a.key})};e.prototype.values=function(){return c(this,function(a){return a.value})};e.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};e.prototype[Symbol.iterator]=
e.prototype.entries;var f=0;return e});function A(a,b,c){120!==b.charCodeAt(0)?a.setAttribute(b,c):109===b.charCodeAt(1)&&108===b.charCodeAt(2)?a.setAttributeNS("http://www.w3.org/XML/1998/namespace",b,c):108===b.charCodeAt(1)&&105===b.charCodeAt(2)?a.setAttributeNS("http://www.w3.org/1999/xlink",b,c):a.setAttribute(b,c)}function B(a,b,c){this.a=a;this.i=b;this.g=null;this.f=c;this.m=this.b=this.h=this.D=this.G=this.u=null}r=B.prototype;r.key=function(a){this.g=a;return this};
r.s=function(a){this.f=a;return this};r.data=function(a){this.f=a;return this};r.style=function(a){this.G=a;return this};r.className=function(a){this.D=a;return this};function C(a,b){a.h=b;return a}r.children=function(a){this.a|=16;this.h=a;return this};r.value=function(a){this.a|=128;this.h=a;return this};r.checked=function(a){this.a|=256;this.h=a;return this};function E(a){if(0===(a.a&4)){if(a=a.h,null!==a&&"string"!==typeof a)for(var b=0;b<a.length;b++)E(a[b])}else ha(a.m)}
function ia(a){if(0===(a.a&4)){if(a=a.h,null!==a&&"string"!==typeof a)for(var b=0;b<a.length;b++)ia(a[b])}else a.m.detach()}function F(a){if(0===(a.a&512))if(0!==(a.a&4)){a=a.m;a.c|=1;null!==a.w&&0===(a.c&65536)&&F(a.w);0!==(a.c&2)&&ja(a);var b=a.A.ca;null!==b&&b(a,a.s,a.state)}else{if(null!==a.h&&(a=a.h,"string"!==typeof a))for(b=0;b<a.length;b++)F(a[b])}else ia(a)}
function ka(a,b){var c=a.a;0!==(c&1)?a.b=document.createTextNode(a.f):0!==(c&2)?a.b=0===(c&131072)?0===(c&32768)?document.createElement(a.i):document.createElementNS("http://www.w3.org/2000/svg",a.i):a.i.createElement():0===(c&512)&&(b=la(a.i,b,a.f),a.b=b.element,a.m=b)}
function ma(a,b){var c,d,e,h,f=a.a,l;if(0!==(f&10)){l=a.b;if(0===(f&262144)){var k=a.f;if(null!==k)for(h=Object.keys(k),c=0,d=h.length;c<d;c++)e=h[c],l[e]=k[e];if(null!==a.u)for(h=Object.keys(a.u),c=0,d=h.length;c<d;c++)e=h[c],A(l,e,a.u[e]);null!==a.G&&(0===(f&32768)?l.style.cssText=a.G:l.setAttribute("style",a.G));null!==a.D&&(0===(f&32768)?l.className=a.D:l.setAttribute("class",a.D))}else 0===(f&8)?a.i.L(l,void 0,a.f):b.A.i.L(l,void 0,a.f);e=a.h;if(null!==e)if(0===(f&4096))if(0===(f&384))if(0===
(f&16))"string"===typeof e?l.textContent=e:G(a,e,null,b);else for(c=0,d=e.length;c<d;c++)G(a,e[c],null,b);else 0!==(a.a&128)?a.b.value=a.h:a.b.checked=a.h;else l.innerHTML=e}else 0!==(f&4)&&H(a.m)}function G(a,b,c,d){a=a.b;null===b.b?(ka(b,d),0!==(b.a&4)&&ha(b.m),ma(b,d),a.insertBefore(b.b,c)):(a.insertBefore(b.b,c),E(b),H(b.m,0===(b.a&1024)?b.f:null))}
function I(a,b,c,d){a=a.b;null===b.b?(ka(b,d),0!==(b.a&4)&&ha(b.m),ma(b,d),a.replaceChild(b.b,c.b)):(a.replaceChild(b.b,c.b),E(b),H(b.m,0===(b.a&1024)?b.f:null));F(c)}function J(a,b){a.b.removeChild(b.b);F(b)}function na(a,b){a.b.textContent="";for(a=0;a<b.length;a++)F(b[a])}
function K(a,b,c){var d=a.b,e=a.a,h;b.b=a.b;if(0!==(e&1))a.f!==b.f&&(a.b.nodeValue=b.f);else if(0!==(e&10)){if(0===(e&262144)){if(a.f!==b.f){h=a.f;var f=b.f,l=Object.keys(h),k,m;for(m=0;m<l.length;m++){k=l[m];var g=f[k];h[k]!==g&&(d[k]=g)}}if(a.u!==b.u)if(0===(a.a&64))for(h=a.u,f=b.u,l=Object.keys(h),m=0;m<l.length;m++)k=l[m],g=f[k],h[k]!==g&&A(d,k,g);else if(h=a.u,f=b.u,null!==h)if(null===f)for(k=Object.keys(h),l=0;l<k.length;l++)d.removeAttribute(k[l]);else{k=Object.keys(h);for(l=0;l<k.length;l++)m=
k[l],f.hasOwnProperty(m)?(g=f[m],h[m]!==g&&A(d,m,g)):d.removeAttribute(m);k=Object.keys(f);for(l=0;l<k.length;l++)m=k[l],h.hasOwnProperty(m)||A(d,m,f[m])}else if(null!==f)for(k=Object.keys(f),l=0;l<k.length;l++)m=k[l],A(d,m,f[m]);a.G!==b.G&&(h=null===b.G?"":b.G,0===(e&32768)?d.style.cssText=h:d.setAttribute("style",h));a.D!==b.D&&(h=null===b.D?"":b.D,0===(e&32768)?d.className=h:d.setAttribute("class",h))}else a.f!==b.f&&(0===(e&8)?a.i.L(d,a.f,b.f):c.A.i.L(d,a.f,b.f));if(0===(a.a&384)){if(a.h!==b.h)if(0===
(a.a&4096))if(d=a.h,b=b.h,0===(a.a&16))null===d?"string"===typeof b?a.b.textContent=b:G(a,b,null,c):null===b?"string"===typeof d?a.b.textContent="":J(a,d):"string"===typeof d?"string"===typeof b?(c=a.b.firstChild)?c.nodeValue=b:a.b.textContent=b:(a.b.textContent="",G(a,b,null,c)):"string"===typeof b?(a.b.textContent=b,F(d)):L(d,b)&&d.g===b.g?K(d,b,c):I(a,b,d,c);else if(null!==d&&0!==d.length)if(null===b||0===b.length)na(a,d);else if(1===d.length&&1===b.length)e=d[0],b=b[0],L(e,b)&&e.g===b.g?K(e,b,
c):I(a,b,e,c);else if(0===(a.a&32)){e=f=0;l=d.length-1;for(h=b.length-1;f<=l&&e<=h;){k=d[f];m=b[e];if(!L(k,m)||k.g!==m.g)break;f++;e++;K(k,m,c)}for(;f<=l&&e<=h;){k=d[l];m=b[h];if(!L(k,m)||k.g!==m.g)break;l--;h--;K(k,m,c)}for(;f<=l&&e<=h;)k=d[f++],m=b[e++],L(k,m)&&k.g===m.g?K(k,m,c):I(a,m,k,c);if(f<=l){do J(a,d[f++]);while(f<=l)}else if(e<=h){d=h+1;d=d<b.length?b[d].b:null;do G(a,b[e++],d,c);while(e<=h)}}else{e=l=0;k=d.length-1;m=b.length-1;f=d[l];h=b[e];var g=d[k],n=b[m],p,y;a:for(;;){for(;f.g===
h.g;){L(f,h)?K(f,h,c):I(a,h,f,c);l++;e++;if(l>k||e>m)break a;f=d[l];h=b[e]}for(;g.g===n.g;){L(g,n)?K(g,n,c):I(a,n,g,c);k--;m--;if(l>k||e>m)break a;g=d[k];n=b[m]}if(g.g===h.g){L(g,h)?K(g,h,c):I(a,h,g,c);a.b.insertBefore(h.b,f.b);k--;e++;if(l>k||e>m)break;g=d[k];h=b[e]}else if(f.g===n.g){L(f,n)?K(f,n,c):I(a,n,f,c);f=m+1;f=f<b.length?b[f].b:null;a.b.insertBefore(n.b,f);l++;m--;if(l>k||e>m)break;f=d[l];n=b[m]}else break}if(l>k)for(f=m+1,f=f<b.length?b[f].b:null;e<=m;)G(a,b[e++],f,c);else if(e>m)for(;l<=
k;)J(a,d[l++]);else{var da=k-l+1,f=m-e+1;h=Array(f);for(g=0;g<f;g++)h[g]=-1;var ea=!1,q=0,D=0;if(4>=f||16>=da*f)for(g=l;g<=k;g++){if(p=d[g],D<f)for(n=e;n<=m;n++)if(y=b[n],p.g===y.g){h[n-e]=g;q>n?ea=!0:q=n;L(p,y)?K(p,y,c):I(a,y,p,c);D++;d[g]=null;break}}else{for(var ya=new Map,g=e;g<=m;g++)p=b[g],ya.set(p.g,g);for(g=l;g<=k;g++)p=d[g],D<f&&(n=ya.get(p.g),void 0!==n&&(y=b[n],h[n-e]=g,q>n?ea=!0:q=n,L(p,y)?K(p,y,c):I(a,y,p,c),D++,d[g]=null))}if(da===d.length&&0===D)for(na(a,d);e<f;)G(a,b[e++],null,c);
else{for(g=da-D;0<g;)p=d[l++],null!==p&&(J(a,p),g--);if(ea){l=h.slice(0);d=[];d.push(0);k=0;for(m=h.length;k<m;k++)if(-1!==h[k])if(g=d[d.length-1],h[g]<h[k])l[k]=g,d.push(k);else{g=0;for(n=d.length-1;g<n;)p=(g+n)/2|0,h[d[p]]<h[k]?g=p+1:n=p;h[k]<h[d[g]]&&(0<g&&(l[k]=d[g-1]),d[g]=k)}g=d.length;for(n=d[g-1];0<g--;)d[g]=n,n=l[n];n=d.length-1;for(g=f-1;0<=g;g--)-1===h[g]?(q=g+e,p=b[q],f=q+1,f=f<b.length?b[f].b:null,G(a,p,f,c)):0>n||g!==d[n]?(q=g+e,p=b[q],f=q+1,f=f<b.length?b[f].b:null,a.b.insertBefore(p.b,
f)):n--}else if(D!==f)for(g=f-1;0<=g;g--)-1===h[g]&&(q=g+e,p=b[q],f=q+1,f=f<b.length?b[f].b:null,G(a,p,f,c))}}}else{if(null!==b)for(e=0;e<b.length;e++)G(a,b[e],null,c)}else d.innerHTML=b.h}else 0!==(e&128)?d.value!==b.h&&(d.value=b.h):d.checked!==b.h&&(d.checked=b.h)}else c=b.m=a.m,0!==(e&2048)&&a.f===b.f||H(c,0===(e&1024)?b.f:void 0)}function L(a,b){return a.a===b.a&&a.i===b.i}function M(a){return new B(2,a,null)}
function N(){this.F=4;this.W=8;this.a=0;this.i="div";this.ca=this.ba=this.$=this.V=this.L=this.da=null}N.prototype.tagName=function(a){this.i=a;"string"!==typeof a&&(this.F|=a.F,this.W|=a.F,this.a|=a.F);return this};N.prototype.canvas=function(){this.F|=65536;this.a|=65536;this.i="canvas";return this};function oa(a){var b=new N;b.V=a;return b}N.prototype.update=function(a){this.L=a;return this};function O(a,b){return new B(4,a,void 0===b?null:b)}
function la(a,b,c){var d;d=0===(a.a&131072)?0===(a.a&32768)?document.createElement(a.i):document.createElementNS("http://www.w3.org/2000/svg",a.i):a.i.createElement();b=new P(a.F,a,d,b,c);0!==(a.a&1)&&(d.ea=b);null!==a.V&&a.V(b,b.s);return b}function P(a,b,c,d,e){this.c=a;this.T=0;this.A=b;this.element=c;this.depth=void 0===d?0:d.depth+1;this.s=void 0===e?null:e;this.state=null;this.w=0===(a&65536)?null:c.getContext("2d");this.H=this.l=null}function Q(a){return new B(a.A.W,a.A.i,null)}
P.prototype.update=function(a){H(this,a)};function R(a,b){null===a.w?(b.m=a,b.b=a.element,ma(b,a)):K(a.w,b,a);a.w=b}P.prototype.I=function(a,b){this.c|=void 0===a?8:a;if(0===(this.c&5)&&(this.c|=4,(void 0===b?0:b)||pa(this),a=qa(),0===(this.c&128))){this.c|=128;b=this.depth;for(a.a|=1;b>=a.N.length;)a.N.push(null);var c=a.N[b];null===c?a.N[b]=[this]:c.push(this)}};function ha(a){ra(a);null!==a.w&&0===(a.c&65536)&&E(a.w)}P.prototype.detach=function(){null!==this.w&&0===(this.c&65536)&&ia(this.w);ja(this)};
P.prototype.subscribe=function(a){var b=new sa(1,a,this,null),c=a.l,d=this.l;null!==c&&(c.K=b,b.o=c);null!==d&&(d.M=b,b.v=d);return this.l=a.l=b};function H(a,b){if(void 0!==b&&0===(a.c&512)){var c=a.s,d=a.A.da;null!==d?d(a,c,b):0===(a.c&4)&&(a.c|=4,pa(a));a.s=b}6===(a.c&6)&&(a.A.L(a,a.s,a.state),a.T=S,a.c&=-133)}function ra(a){a.c|=2;var b=a.A.$;null!==b&&b(a,a.s,a.state)}function ja(a){a.c&=-19;for(var b=a.l;null!==b;)ta(b),b=b.v;a.l=null;pa(a);b=a.A.ba;null!==b&&b(a,a.s,a.state)}
function pa(a){for(var b=a.H;null!==b;)ta(b),b=b.v;a.H=null}function T(){this.a=0;this.N=[];this.J=this.X=this.O=this.P=null}T.prototype.write=function(a){this.a|=2;null===this.P&&(this.P=[]);this.P.push(a)};T.prototype.read=function(a){this.a|=4;null===this.O&&(this.O=[]);this.O.push(a)};T.prototype.focus=function(a){this.J=a};var U=0,S=0,ua=[],va=[],wa=new T,xa=new T,V=[],za=document.createTextNode(""),Aa="__kivi"+Math.random();(new MutationObserver(Ba)).observe(za,{characterData:!0});
window.addEventListener("message",Ca);function Da(){0===(U&4)&&(U|=4,requestAnimationFrame(Ea))}function Ca(a){if(a.source===window&&a.data===Aa){U&=-3;a=va;va=[];for(var b=0;b<a.length;b++)a[b]();S++}}
function Ea(){var a,b;U&=-5;var c=xa;xa=wa;wa=c;for(b=0;b<V.length;b++)V[b].c|=4;do{for(;0!==(c.a&4);)for(c.a&=-5,a=c.O,c.O=null,b=0;b<a.length;b++)a[b]();for(;0!==(c.a&3);){if(0!==(c.a&1)){c.a&=-2;var d=c.N;for(b=0;b<d.length;b++){var e=d[b];if(null!==e)for(d[b]=null,a=0;a<e.length;a++)H(e[a])}}if(0!==(c.a&2))for(c.a&=-3,a=c.P,c.P=null,b=0;b<a.length;b++)a[b]()}b=0;for(a=V.length;b<a;)d=V[b++],0===(d.c&16)?(d.c&=-33,b===a?V.pop():V[--b]=V.pop()):H(d)}while(0!==(c.a&7));for(;0!==(c.a&8);)for(c.a&=
-9,a=c.X,c.X=null,b=0;b<a.length;b++)a[b]();null!==c.J&&(c.J.constructor===B?c.J.b.focus():c.J.focus(),c.J=null);0<V.length&&Da();S++}function Ba(){for(;0<ua.length;){var a=ua;ua=[];for(var b=0;b<a.length;b++)a[b]();S++}U&=-2}function qa(){Da();return xa}function sa(a,b,c,d){this.a=a;this.Z=b;this.U=c;this.aa=d;this.v=this.M=this.o=this.K=null}function ta(a){null===a.K?0===(a.a&2)?a.Z.l=a.o:a.Z.H=a.o:a.K.o=a.o;null!==a.o&&(a.o.K=a.K)}
sa.prototype.cancel=function(){ta(this);0!==(this.a&1)&&(null===this.M?0===(this.a&2)?this.U.l=this.v:this.U.H=this.v:this.M.v=this.v,null!==this.v&&(this.v.M=this.M))};function Fa(a){0!==(a.a&1)?a.U.I():a.aa()}function Ga(){this.T=S;this.H=this.l=null}Ga.prototype.subscribe=function(a){a=new sa(0,this,null,a);var b=this.l;null!==b&&(b.K=a,a.o=b);return this.l=a};Ga.prototype.I=function(){var a=S;if(this.T<a){this.T=a;for(a=this.l;null!==a;)Fa(a),a=a.o;for(a=this.H;null!==a;)Fa(a),a=a.o;this.H=null}};
var W,Ha,X=0,Ia=0,Y=new Ga,Ja=0,Ka=new Map,Z=null;
function La(a,b){if(Ja===a){for(var c=[],d=0;d<b.length;d++){var e=b[d].docId;Ka.has(e)||c.push(e)}0<c.length?(new Promise(function(a,b){var d=Ha.transaction("comments");d.onerror=function(a){b(a.message)};d.oncomplete=function(){a()};for(var d=d.objectStore("comments"),e={},f=0;f<c.length;e={key:e.key},f++)e.key=c[f],d.get(c[f]).onsuccess=function(a){return function(b){(b=b.target.result)&&Ka.set(a.key,b)}}(e)})).then(function(){Ja===a&&(Z=b,X=1,Y.I())}):(Z=b,X=1,Y.I())}}
function Ma(){return new Promise(function(a,b){var c=indexedDB.open("docs",1);c.onerror=function(a){b(a.message)};c.onsuccess=function(){a(c.result)}})}window.wwState(function(a,b){void 0===W&&(W=a,W.addEventListener("message",function(a){"number"!==typeof a.data&&(a=a.data,1===a.type&&La(a.id,a.payload))}));Ia=b;Y.I();2<b&&void 0===Ha&&Ma().then(function(a){Ha=a;X=1;Y.I()})});
var Oa=oa(function(a){a.state="";a.element.oninput=Na}).update(function(a,b,c){R(a,C(Q(a).className("search-field"),M("input").s({placeholder:"Type to search"}).value(c)))}),Na=function(a){Oa.a|=1;return function(b,c){if(void 0===c||!c.ga()){var d;a:{d=b.target;for(var e=b.currentTarget,e=void 0===e?null:e;d!==e;){if(d.matches("input"))break a;d=d.parentNode}d=null}null!==d&&(e=b.currentTarget.ea,a(b,e,e.s,e.state,d,c))}}}(function(a,b,c,d,e){a=e.value;a!==d&&(b.state=a,b=++Ja,a?(W.postMessage({id:b,
type:1,payload:a}),X=2):X=1,Z=null,Y.I())}),Pa=(new N).update(function(a,b){R(a,Q(a).className("result").children([C(M("div").className("result-score"),b.fa.toString()),C(M("div").className("result-author"),b.Y.author),C(M("div").className("result-body"),b.Y.body)]))}),Qa=(new N).update(function(a){var b=[];if(1===X){if(null!==Z)for(var c=0;c<Z.length;c++){var d=Z[c],e=Ka.get(d.docId);void 0!==e&&b.push(O(Pa,{Y:e,fa:d.score}))}}else b.push(M("div").className("spinner"));R(a,Q(a).className("search-results").children(b))});
function Ra(a){switch(a){case 0:return"Waiting for a Web Worker";case 1:return"Worker is Ready";case 2:return"Loading Documents";case 3:return"Saving Documents to the IndexedDB";case 4:return"Indexing Documents"}return""}var Sa=(new N).update(function(a,b){R(a,Q(a).className("main-progress").children([M("div").className("spinner"),C(M("div").className("main-progress-text"),Ra(b))]))}),Ta=(new N).update(function(a){R(a,Q(a).className("search-view").children([O(Oa),O(Qa)]))});
(function(a,b,c,d){var e=la(a,void 0,c);d?(b.appendChild(e.element),ra(e),H(e)):qa().write(function(){b.appendChild(e.element);ra(e);H(e)});return e})(oa(function(a){a.subscribe(Y)}).update(function(a){var b=Q(a).className("main"),c;0<X&&5===Ia?c=O(Ta):(c=Ia,c=new B(2052,Sa,void 0===c?null:c));R(a,C(b,c))}),document.getElementById("app"));}).call(this);
