(function(){'use strict';var p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this,q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};function r(){r=function(){};p.Symbol||(p.Symbol=t)}var v=0;function t(a){return"jscomp_symbol_"+(a||"")+v++}
function w(){r();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&q(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return x(this)}});w=function(){}}function x(a){var d=0;return y(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})}function y(a){w();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function z(a){w();var d=a[Symbol.iterator];return d?d.call(a):x(a)}
function A(a,d){return Object.prototype.hasOwnProperty.call(a,d)}function C(a,d){if(d){var b=p;a=a.split(".");for(var c=0;c<a.length-1;c++){var e=a[c];e in b||(b[e]={});b=b[e]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&q(b,a,{configurable:!0,writable:!0,value:d})}}
C("WeakMap",function(a){function d(a){this.m=(g+=Math.random()+1).toString();if(a){r();w();a=z(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}function b(a){A(a,e)||q(a,e,{value:{}})}function c(a){var c=Object[a];c&&(Object[a]=function(a){b(a);return c(a)})}if(function(){if(!a||!Object.seal)return!1;try{var c=Object.seal({}),b=Object.seal({}),d=new a([[c,2],[b,3]]);if(2!=d.get(c)||3!=d.get(b))return!1;d.delete(c);d.set(b,4);return!d.has(c)&&4==d.get(b)}catch(n){return!1}}())return a;
var e="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");c("seal");var g=0;d.prototype.set=function(a,c){b(a);if(!A(a,e))throw Error("WeakMap key fail: "+a);a[e][this.m]=c;return this};d.prototype.get=function(a){return A(a,e)?a[e][this.m]:void 0};d.prototype.has=function(a){return A(a,e)&&A(a[e],this.m)};d.prototype.delete=function(a){return A(a,e)&&A(a[e],this.m)?delete a[e][this.m]:!1};return d});
C("Map",function(a){function d(){var a={};return a.c=a.next=a.head=a}function b(a,c){var b=a.b;return y(function(){if(b){for(;b.head!=a.b;)b=b.c;for(;b.next!=b.head;)return b=b.next,{done:!1,value:c(b)};b=null}return{done:!0,value:void 0}})}function c(a,c){var b;b=c&&typeof c;"object"==b||"function"==b?g.has(c)?b=g.get(c):(b=""+ ++f,g.set(c,b)):b="p_"+c;var d=a.l[b];if(d&&A(a.l,b))for(a=0;a<d.length;a++){var e=d[a];if(c!==c&&e.key!==e.key||c===e.key)return{id:b,list:d,index:a,a:e}}return{id:b,list:d,
index:-1,a:void 0}}function e(a){this.l={};this.b=d();this.size=0;if(a){a=z(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),b=new a(z([[c,"s"]]));if("s"!=b.get(c)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var d=b.entries(),e=d.next();if(e.done||e.value[0]!=c||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?
!1:!0}catch(l){return!1}}())return a;r();w();var g=new WeakMap;e.prototype.set=function(a,b){var d=c(this,a);d.list||(d.list=this.l[d.id]=[]);d.a?d.a.value=b:(d.a={next:this.b,c:this.b.c,head:this.b,key:a,value:b},d.list.push(d.a),this.b.c.next=d.a,this.b.c=d.a,this.size++);return this};e.prototype.delete=function(a){a=c(this,a);return a.a&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.l[a.id],a.a.c.next=a.a.next,a.a.next.c=a.a.c,a.a.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.l=
{};this.b=this.b.c=d();this.size=0};e.prototype.has=function(a){return!!c(this,a).a};e.prototype.get=function(a){return(a=c(this,a).a)&&a.value};e.prototype.entries=function(){return b(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return b(this,function(a){return a.key})};e.prototype.values=function(){return b(this,function(a){return a.value})};e.prototype.forEach=function(a,c){for(var b=this.entries(),d;!(d=b.next()).done;)d=d.value,a.call(c,d[1],d[0],this)};e.prototype[Symbol.iterator]=
e.prototype.entries;var f=0;return e});C("Array.prototype.fill",function(a){return a?a:function(a,b,c){var d=this.length||0;0>b&&(b=Math.max(0,d+b));if(null==c||c>d)c=d;c=Number(c);0>c&&(c=Math.max(0,d+c));for(b=Number(b||0);b<c;b++)this[b]=a;return this}});var D=/[\s]+/;function E(a){return a.trim().split(D)}var F=/^\W+/,G=/\W+$/;function H(a){this.charCode=a;this.g=this.firstChild=this.next=null}
function I(a,d,b){for(;b<d.length;b++){var c=new H(d.charCodeAt(b));null!==a.firstChild&&(c.next=a.firstChild);a=a.firstChild=c}return a}function J(a,d){for(a=a.firstChild;null!==a;){if(a.charCode===d)return a;a=a.next}}function M(){this.root=new H(0)}M.prototype.get=function(a){for(var d=this.root,b=0;b<a.length;b++)if(d=J(d,a.charCodeAt(b)),void 0===d)return null;return d};
M.prototype.add=function(a,d,b){for(var c=this.root,e=0;e<a.length;e++){if(null===c.firstChild){c=I(c,a,e);break}var g=J(c,a.charCodeAt(e));if(void 0===g){c=I(c,a,e);break}c=g}a={next:null,i:d,L:b};null!==c.g&&(a.next=c.g);c.g=a};M.prototype.v=function(a){var d=this.get(a),b=[];null!==d&&N(d,b,a);return b};function N(a,d,b){null!==a.g&&null!==a.g&&d.push(b);for(a=a.firstChild;null!==a;)N(a,d,b+String.fromCharCode(a.charCode)),a=a.next}
function O(a){return a.toLowerCase().replace(F,"").replace(G,"")}function P(a){this.h=new Map;this.o=new M;this.f=[];this.G=E;this.F=O;this.D=1.2;this.C=.75;void 0!==a&&(a=a.M,void 0!==a&&(void 0!==a.K&&(this.D=a.K),void 0!==a.H&&(this.C=a.H)))}function Q(a){var d=R,b,c;void 0===b&&(b=a);void 0===c&&(c=1);d.f.push({name:a,J:b,I:c,j:0,u:0})}
P.prototype.add=function(a,d){for(var b=this,c=Array(this.f.length),e=new Map,g=0;g<this.f.length;g++){var f=this.f[g],m=f.J,m="string"===typeof m?d[m]:m(d);if(void 0===m)c[g]=0;else{for(var m=this.G(m),h=0,n=0;n<m.length;n++){var k=this.F(m[n]);if(""!==k){h++;var l=e.get(k);void 0===l&&(l=Array(this.f.length).fill(0),e.set(k,l));l[g]+=1}}f.j+=h;f.u=f.j/(this.h.size+1);c[g]=h}}var u={s:a,A:!1,w:c};this.h.set(a,u);e.forEach(function(a,c){b.o.add(c,u,a)})};
P.prototype.remove=function(a){var d=this.h.get(a);if(void 0!==d)for(d.A=!0,this.h.delete(a),a=0;a<this.f.length;a++){var b=d.w[a];if(0<b){var c=this.f[a];c.j-=b;c.u=c.j/this.h.size}}};
P.prototype.search=function(a){a=this.G(a);for(var d=new Map,b=0;b<a.length;b++){var c=this.F(a[b]);if(""!==c)for(var e=this.o.v(c),g=0;g<e.length;g++){var f=e[g],m=f===c?1:Math.log(1+1/(f.length-c.length)),h=this.o.get(f);if(null!==h&&null!==h.g){for(var n=0,f=h.g;null!==f;)f.i.A||n++,f=f.next;if(0<n)for(n=Math.log(1+(this.size-n+.5)/(n+.5)),f=h.g;null!==f;){if(!f.i.A){for(var k=h=0;k<f.i.w.length;k++){var l=f.L[k];if(0<l)var u=this.f[k],K=this.D,L=this.C,l=(K+1)*l/(K*(1-L+f.i.w[k]/u.u*L)+l),h=h+
l*n*u.I*m}0<h&&(k=d.get(f.i.s),d.set(f.i.s,void 0===k?h:k+h))}f=f.next}}}}var B=[];d.forEach(function(a,c){B.push({s:c,B:a})});B.sort(function(a,c){return c.B-a.B});return B};P.prototype.v=function(a){return this.o.v(a)};p.Object.defineProperties(P.prototype,{size:{configurable:!0,enumerable:!0,get:function(){return this.h.size}}});postMessage(1);
function S(){return new Promise(function(a,d){var b=new XMLHttpRequest;b.onload=function(){var c=[];JSON.parse(b.responseText).forEach(function(a){c.push(a)});a(c)};b.onerror=function(a){d(a.message)};b.open("GET","reddit_comments.json");b.send()})}var R=new P;Q("author");Q("body");var T=!1;onmessage=function(a){if(T&&(a=a.data,1===a.type)){var d=R.search(a.payload);postMessage({id:a.id,type:1,payload:d.slice(0,50).map(function(a){return{docId:a.s,score:a.B}})})}};var U;
(new Promise(function(a,d){var b=indexedDB.open("docs",1);b.onerror=function(a){d(a.message)};b.onsuccess=function(c){a(c.target.result)};b.onupgradeneeded=function(a){a=a.target.result;a.objectStoreNames.contains("comments")||a.createObjectStore("comments",{autoIncrement:!0})}})).then(function(a){U=a;return new Promise(function(d,b){var c=a.transaction("comments").objectStore("comments").count();c.onerror=function(a){b(a.message)};c.onsuccess=function(){d(c.result)}})}).then(function(a){return 0===
a?(postMessage(2),S().then(function(a){return new Promise(function(b,c){postMessage(3);var d=U.transaction("comments","readwrite");d.onerror=function(a){c(a.message)};d.oncomplete=function(){b()};var g=d.objectStore("comments");a.forEach(function(a){g.add(a)})})})):Promise.resolve()}).then(function(){return new Promise(function(a,d){postMessage(4);var b=U.transaction("comments");b.onerror=function(a){d(a.message)};b.oncomplete=function(){a()};b.objectStore("comments").openCursor().onsuccess=function(a){if(a=
a.target.result)R.add(a.key,a.value),a.continue()}})}).then(function(){postMessage(5);T=!0});}).call(this);
