(function(){'use strict';var n="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this,p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(d.get||d.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};function r(){r=function(){};n.Symbol||(n.Symbol=t)}var u=0;function t(a){return"jscomp_symbol_"+(a||"")+u++}
function v(){r();var a=n.Symbol.iterator;a||(a=n.Symbol.iterator=n.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return x(this)}});v=function(){}}function x(a){var c=0;return y(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})}function y(a){v();a={next:a};a[n.Symbol.iterator]=function(){return this};return a}function z(a){v();var c=a[Symbol.iterator];return c?c.call(a):x(a)}
function A(a,c){return Object.prototype.hasOwnProperty.call(a,c)}function C(a,c){if(c){var d=n;a=a.split(".");for(var b=0;b<a.length-1;b++){var f=a[b];f in d||(d[f]={});d=d[f]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&p(d,a,{configurable:!0,writable:!0,value:c})}}
C("WeakMap",function(a){function c(a){this.s=(g+=Math.random()+1).toString();if(a){r();v();a=z(a);for(var e;!(e=a.next()).done;)e=e.value,this.set(e[0],e[1])}}function d(a){A(a,f)||p(a,f,{value:{}})}function b(a){var e=Object[a];e&&(Object[a]=function(a){d(a);return e(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),e=Object.seal({}),d=new a([[b,2],[e,3]]);if(2!=d.get(b)||3!=d.get(e))return!1;d.delete(b);d.set(e,4);return!d.has(b)&&4==d.get(e)}catch(k){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random().toString().substring(2);b("freeze");b("preventExtensions");b("seal");var g=0;c.prototype.set=function(a,e){d(a);if(!A(a,f))throw Error("WeakMap key fail: "+a);a[f][this.s]=e;return this};c.prototype.get=function(a){return A(a,f)?a[f][this.s]:void 0};c.prototype.has=function(a){return A(a,f)&&A(a[f],this.s)};c.prototype.delete=function(a){return A(a,f)&&A(a[f],this.s)?delete a[f][this.s]:!1};return c});
C("Map",function(a){function c(){var a={};return a.g=a.next=a.head=a}function d(a,d){var b=a.f;return y(function(){if(b){for(;b.head!=a.f;)b=b.g;for(;b.next!=b.head;)return b=b.next,{done:!1,value:d(b)};b=null}return{done:!0,value:void 0}})}function b(a,b){var d;d=b&&typeof b;"object"==d||"function"==d?g.has(b)?d=g.get(b):(d=""+ ++l,g.set(b,d)):d="p_"+b;var e=a.o[d];if(e&&A(a.o,d))for(a=0;a<e.length;a++){var c=e[a];if(b!==b&&c.key!==c.key||b===c.key)return{id:d,list:e,index:a,a:c}}return{id:d,list:e,
index:-1,a:void 0}}function f(a){this.o={};this.f=c();this.size=0;if(a){a=z(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(z([[b,"s"]]));if("s"!=d.get(b)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var c=d.entries(),f=c.next();if(f.done||f.value[0]!=b||"s"!=f.value[1])return!1;f=c.next();return f.done||4!=f.value[0].x||"t"!=f.value[1]||!c.next().done?
!1:!0}catch(h){return!1}}())return a;r();v();var g=new WeakMap;f.prototype.set=function(a,d){var c=b(this,a);c.list||(c.list=this.o[c.id]=[]);c.a?c.a.value=d:(c.a={next:this.f,g:this.f.g,head:this.f,key:a,value:d},c.list.push(c.a),this.f.g.next=c.a,this.f.g=c.a,this.size++);return this};f.prototype.delete=function(a){a=b(this,a);return a.a&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.o[a.id],a.a.g.next=a.a.next,a.a.next.g=a.a.g,a.a.head=null,this.size--,!0):!1};f.prototype.clear=function(){this.o=
{};this.f=this.f.g=c();this.size=0};f.prototype.has=function(a){return!!b(this,a).a};f.prototype.get=function(a){return(a=b(this,a).a)&&a.value};f.prototype.entries=function(){return d(this,function(a){return[a.key,a.value]})};f.prototype.keys=function(){return d(this,function(a){return a.key})};f.prototype.values=function(){return d(this,function(a){return a.value})};f.prototype.forEach=function(a,b){for(var d=this.entries(),c;!(c=d.next()).done;)c=c.value,a.call(b,c[1],c[0],this)};f.prototype[Symbol.iterator]=
f.prototype.entries;var l=0;return f});C("Array.prototype.fill",function(a){return a?a:function(a,d,b){var c=this.length||0;0>d&&(d=Math.max(0,c+d));if(null==b||b>c)b=c;b=Number(b);0>b&&(b=Math.max(0,c+b));for(d=Number(d||0);d<b;d++)this[d]=a;return this}});
C("Set",function(a){function c(a){this.b=new Map;if(a){a=z(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.b.size}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var d=Object.seal({x:4}),b=new a(z([d]));if(!b.has(d)||1!=b.size||b.add(d)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var c=b.entries(),g=c.next();if(g.done||g.value[0]!=d||g.value[1]!=d)return!1;g=c.next();return g.done||g.value[0]==d||4!=g.value[0].x||g.value[1]!=g.value[0]?
!1:c.next().done}catch(l){return!1}}())return a;r();v();c.prototype.add=function(a){this.b.set(a,a);this.size=this.b.size;return this};c.prototype.delete=function(a){a=this.b.delete(a);this.size=this.b.size;return a};c.prototype.clear=function(){this.b.clear();this.size=0};c.prototype.has=function(a){return this.b.has(a)};c.prototype.entries=function(){return this.b.entries()};c.prototype.values=function(){return this.b.values()};c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=
function(a,b){var d=this;this.b.forEach(function(c){return a.call(b,c,c,d)})};return c});var D=/[\s]+/;function E(a){return a.trim().split(D)}var F=/^\W+/,G=/\W+$/;function H(a){this.charCode=a;this.c=this.firstChild=this.next=null}function I(a,c,d){for(;d<c.length;d++){var b=new H(c.charCodeAt(d));null!==a.firstChild&&(b.next=a.firstChild);a=a.firstChild=b}return a}function J(a,c){for(a=a.firstChild;null!==a;){if(a.charCode===c)return a;a=a.next}}function N(){this.root=new H(0)}
N.prototype.get=function(a){for(var c=this.root,d=0;d<a.length;d++)if(c=J(c,a.charCodeAt(d)),void 0===c)return null;return c};N.prototype.add=function(a,c,d){for(var b=this.root,f=0;f<a.length;f++){if(null===b.firstChild){b=I(b,a,f);break}var g=J(b,a.charCodeAt(f));if(void 0===g){b=I(b,a,f);break}b=g}a={next:null,i:c,M:d};null!==b.c&&(a.next=b.c);b.c=a};N.prototype.w=function(a){var c=this.get(a),d=[];null!==c&&O(c,d,a);return d};
function O(a,c,d){null!==a.c&&null!==a.c&&c.push(d);for(a=a.firstChild;null!==a;)O(a,c,d+String.fromCharCode(a.charCode)),a=a.next}function P(a){return a.toLowerCase().replace(F,"").replace(G,"")}function Q(a){this.j=new Map;this.u=new N;this.h=[];this.H=E;this.G=P;this.F=1.2;this.D=.75;void 0!==a&&(a=a.N,void 0!==a&&(void 0!==a.L&&(this.F=a.L),void 0!==a.I&&(this.D=a.I)))}function R(a){var c=S,d,b;void 0===d&&(d=a);void 0===b&&(b=1);c.h.push({name:a,K:d,J:b,m:0,v:0})}
Q.prototype.add=function(a,c){for(var d=this,b=Array(this.h.length),f=new Map,g=0;g<this.h.length;g++){var l=this.h[g],e=l.K,e="string"===typeof e?c[e]:e(c);if(void 0===e)b[g]=0;else{for(var e=this.H(e),w=0,k=0;k<e.length;k++){var m=this.G(e[k]);if(""!==m){w++;var h=f.get(m);void 0===h&&(h=Array(this.h.length).fill(0),f.set(m,h));h[g]+=1}}l.m+=w;l.v=l.m/(this.j.size+1);b[g]=w}}var q={l:a,B:!1,A:b};this.j.set(a,q);f.forEach(function(a,b){d.u.add(b,q,a)})};
Q.prototype.remove=function(a){var c=this.j.get(a);if(void 0!==c)for(c.B=!0,this.j.delete(a),a=0;a<this.h.length;a++){var d=c.A[a];if(0<d){var b=this.h[a];b.m-=d;b.v=b.m/this.j.size}}};
Q.prototype.search=function(a){a=this.H(a);for(var c=new Map,d=0;d<a.length;d++){var b=this.G(a[d]);if(""!==b)for(var f=this.u.w(b),g=new Set,l=0;l<f.length;l++){var e=f[l],w=e===b?1:Math.log(1+1/(e.length-b.length)),k=this.u.get(e);if(null!==k&&null!==k.c){for(var m=0,e=k.c,h=null;null!==e;)e.i.B?null===h?k.c=e.next:h.next=e.next:(h=e,m++),e=e.next;if(0<m)for(m=Math.log(1+(this.size-m+.5)/(m+.5)),e=k.c;null!==e;){if(!e.i.B&&!g.has(e.i.l)){for(h=k=0;h<e.i.A.length;h++){var q=e.M[h];if(0<q)var K=this.h[h],
L=this.F,M=this.D,q=(L+1)*q/(L*(1-M+e.i.A[h]/K.v*M)+q),k=k+q*m*K.J*w}0<k&&(h=c.get(e.i.l),c.set(e.i.l,void 0===h?k:h+k),g.add(e.i.l))}e=e.next}}}}var B=[];c.forEach(function(a,b){B.push({l:b,C:a})});B.sort(function(a,b){return b.C-a.C});return B};Q.prototype.w=function(a){return this.u.w(a)};n.Object.defineProperties(Q.prototype,{size:{configurable:!0,enumerable:!0,get:function(){return this.j.size}}});postMessage(1);
function T(){return new Promise(function(a,c){var d=new XMLHttpRequest;d.onload=function(){var b=[];JSON.parse(d.responseText).forEach(function(a){b.push(a)});a(b)};d.onerror=function(a){c(a.message)};d.open("GET","reddit_comments.json");d.send()})}var S=new Q;R("author");R("body");var U=!1;onmessage=function(a){if(U&&(a=a.data,1===a.type)){var c=S.search(a.payload);postMessage({id:a.id,type:1,payload:c.slice(0,50).map(function(a){return{docId:a.l,score:a.C}})})}};var V;
(new Promise(function(a,c){var d=indexedDB.open("docs",1);d.onerror=function(a){c(a.message)};d.onsuccess=function(b){a(b.target.result)};d.onupgradeneeded=function(a){a=a.target.result;a.objectStoreNames.contains("comments")||a.createObjectStore("comments",{autoIncrement:!0})}})).then(function(a){V=a;return new Promise(function(c,d){var b=a.transaction("comments").objectStore("comments").count();b.onerror=function(a){d(a.message)};b.onsuccess=function(){c(b.result)}})}).then(function(a){return 0===
a?(postMessage(2),T().then(function(a){return new Promise(function(d,b){postMessage(3);var c=V.transaction("comments","readwrite");c.onerror=function(a){b(a.message)};c.oncomplete=function(){d()};var g=c.objectStore("comments");a.forEach(function(a){g.add(a)})})})):Promise.resolve()}).then(function(){return new Promise(function(a,c){postMessage(4);var d=V.transaction("comments");d.onerror=function(a){c(a.message)};d.oncomplete=function(){a()};d.objectStore("comments").openCursor().onsuccess=function(a){if(a=
a.target.result)S.add(a.key,a.value),a.continue()}})}).then(function(){postMessage(5);U=!0});}).call(this);
