(function(){'use strict';var p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this,q="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){if(b.get||b.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};function r(){r=function(){};p.Symbol||(p.Symbol=t)}var u=0;function t(a){return"jscomp_symbol_"+(a||"")+u++}
function w(){r();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&q(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return x(this)}});w=function(){}}function x(a){var d=0;return y(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})}function y(a){w();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function z(a){w();var d=a[Symbol.iterator];return d?d.call(a):x(a)}
function A(a,d){return Object.prototype.hasOwnProperty.call(a,d)}function C(a,d){if(d){var b=p;a=a.split(".");for(var c=0;c<a.length-1;c++){var e=a[c];e in b||(b[e]={});b=b[e]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&q(b,a,{configurable:!0,writable:!0,value:d})}}
C("WeakMap",function(a){function d(a){this.u=(g+=Math.random()+1).toString();if(a){r();w();a=z(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}function b(a){A(a,e)||q(a,e,{value:{}})}function c(a){var c=Object[a];c&&(Object[a]=function(a){b(a);return c(a)})}if(function(){if(!a||!Object.seal)return!1;try{var c=Object.seal({}),b=Object.seal({}),d=new a([[c,2],[b,3]]);if(2!=d.get(c)||3!=d.get(b))return!1;d.delete(c);d.set(b,4);return!d.has(c)&&4==d.get(b)}catch(n){return!1}}())return a;
var e="$jscomp_hidden_"+Math.random().toString().substring(2);c("freeze");c("preventExtensions");c("seal");var g=0;d.prototype.set=function(a,c){b(a);if(!A(a,e))throw Error("WeakMap key fail: "+a);a[e][this.u]=c;return this};d.prototype.get=function(a){return A(a,e)?a[e][this.u]:void 0};d.prototype.has=function(a){return A(a,e)&&A(a[e],this.u)};d.prototype.delete=function(a){return A(a,e)&&A(a[e],this.u)?delete a[e][this.u]:!1};return d});
C("Map",function(a){function d(){var a={};return a.h=a.next=a.head=a}function b(a,c){var b=a.g;return y(function(){if(b){for(;b.head!=a.g;)b=b.h;for(;b.next!=b.head;)return b=b.next,{done:!1,value:c(b)};b=null}return{done:!0,value:void 0}})}function c(a,c){var b;b=c&&typeof c;"object"==b||"function"==b?g.has(c)?b=g.get(c):(b=""+ ++f,g.set(c,b)):b="p_"+c;var d=a.s[b];if(d&&A(a.s,b))for(a=0;a<d.length;a++){var e=d[a];if(c!==c&&e.key!==e.key||c===e.key)return{id:b,list:d,index:a,a:e}}return{id:b,list:d,
index:-1,a:void 0}}function e(a){this.s={};this.g=d();this.size=0;if(a){a=z(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),b=new a(z([[c,"s"]]));if("s"!=b.get(c)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var d=b.entries(),e=d.next();if(e.done||e.value[0]!=c||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?
!1:!0}catch(m){return!1}}())return a;r();w();var g=new WeakMap;e.prototype.set=function(a,b){var d=c(this,a);d.list||(d.list=this.s[d.id]=[]);d.a?d.a.value=b:(d.a={next:this.g,h:this.g.h,head:this.g,key:a,value:b},d.list.push(d.a),this.g.h.next=d.a,this.g.h=d.a,this.size++);return this};e.prototype.delete=function(a){a=c(this,a);return a.a&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.s[a.id],a.a.h.next=a.a.next,a.a.next.h=a.a.h,a.a.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.s=
{};this.g=this.g.h=d();this.size=0};e.prototype.has=function(a){return!!c(this,a).a};e.prototype.get=function(a){return(a=c(this,a).a)&&a.value};e.prototype.entries=function(){return b(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return b(this,function(a){return a.key})};e.prototype.values=function(){return b(this,function(a){return a.value})};e.prototype.forEach=function(a,c){for(var b=this.entries(),d;!(d=b.next()).done;)d=d.value,a.call(c,d[1],d[0],this)};e.prototype[Symbol.iterator]=
e.prototype.entries;var f=0;return e});C("Array.prototype.fill",function(a){return a?a:function(a,b,c){var d=this.length||0;0>b&&(b=Math.max(0,d+b));if(null==c||c>d)c=d;c=Number(c);0>c&&(c=Math.max(0,d+c));for(b=Number(b||0);b<c;b++)this[b]=a;return this}});
function D(a,d,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""}C("String.prototype.endsWith",function(a){return a?a:function(a,b){var c=D(this,a,"endsWith");a+="";void 0===b&&(b=c.length);b=Math.max(0,Math.min(b|0,c.length));for(var d=a.length;0<d&&0<b;)if(c[--b]!=a[--d])return!1;return 0>=d}});
C("String.prototype.startsWith",function(a){return a?a:function(a,b){var c=D(this,a,"startsWith");a+="";var d=c.length,g=a.length;b=Math.max(0,Math.min(b|0,c.length));for(var f=0;f<g&&b<d;)if(c[b++]!=a[f++])return!1;return f>=g}});var E=/[\s]+/;function F(a){return a.trim().split(E)}var aa=/^\W+/,ba=/\W+$/;function G(a){this.charCode=a;this.j=this.firstChild=this.next=null}
function H(a,d,b){for(;b<d.length;b++){var c=new G(d.charCodeAt(b));null!==a.firstChild&&(c.next=a.firstChild);a=a.firstChild=c}return a}function I(a,d){for(a=a.firstChild;null!==a;){if(a.charCode===d)return a;a=a.next}}function J(){this.root=new G(0)}J.prototype.get=function(a){for(var d=this.root,b=0;b<a.length;b++)if(d=I(d,a.charCodeAt(b)),void 0===d)return null;return d};
J.prototype.add=function(a,d,b){for(var c=this.root,e=0;e<a.length;e++){if(null===c.firstChild){c=H(c,a,e);break}var g=I(c,a.charCodeAt(e));if(void 0===g){c=H(c,a,e);break}c=g}a={next:null,m:d,N:b};null!==c.j&&(a.next=c.j);c.j=a};J.prototype.C=function(a){var d=this.get(a),b=[];null!==d&&K(d,b,a);return b};function K(a,d,b){null!==a.j&&null!==a.j&&d.push(b);for(a=a.firstChild;null!==a;)K(a,d,b+String.fromCharCode(a.charCode)),a=a.next}
function ca(a){return a.toLowerCase().replace(aa,"").replace(ba,"")}function N(a){this.l=new Map;this.v=new J;this.i=[];this.J=F;this.A=ca;this.I=1.2;this.H=.75;void 0!==a&&(a=a.O,void 0!==a&&(void 0!==a.M&&(this.I=a.M),void 0!==a.b&&(this.H=a.b)))}function O(a){var d=P,b,c;void 0===b&&(b=a);void 0===c&&(c=1);d.i.push({name:a,L:b,K:c,o:0,B:0})}
N.prototype.add=function(a,d){for(var b=this,c=Array(this.i.length),e=new Map,g=0;g<this.i.length;g++){var f=this.i[g],h=f.L,h="string"===typeof h?d[h]:h(d);if(void 0===h)c[g]=0;else{for(var h=this.J(h),k=0,n=0;n<h.length;n++){var l=this.A(h[n]);if(""!==l){k++;var m=e.get(l);void 0===m&&(m=Array(this.i.length).fill(0),e.set(l,m));m[g]+=1}}f.o+=k;f.B=f.o/(this.l.size+1);c[g]=k}}var v={w:a,F:!1,D:c};this.l.set(a,v);e.forEach(function(a,c){b.v.add(c,v,a)})};
N.prototype.remove=function(a){var d=this.l.get(a);if(void 0!==d)for(d.F=!0,this.l.delete(a),a=0;a<this.i.length;a++){var b=d.D[a];if(0<b){var c=this.i[a];c.o-=b;c.B=c.o/this.l.size}}};
N.prototype.search=function(a){a=this.J(a);for(var d=new Map,b=0;b<a.length;b++){var c=this.A(a[b]);if(""!==c)for(var e=this.v.C(c),g=0;g<e.length;g++){var f=e[g],h=f===c?1:Math.log(1+1/(f.length-c.length)),k=this.v.get(f);if(null!==k&&null!==k.j){for(var n=0,f=k.j;null!==f;)f.m.F||n++,f=f.next;if(0<n)for(n=Math.log(1+(this.size-n+.5)/(n+.5)),f=k.j;null!==f;){if(!f.m.F){for(var l=k=0;l<f.m.D.length;l++){var m=f.N[l];if(0<m)var v=this.i[l],L=this.I,M=this.H,m=(L+1)*m/(L*(1-M+f.m.D[l]/v.B*M)+m),k=k+
m*n*v.K*h}0<k&&(l=d.get(f.m.w),d.set(f.m.w,void 0===l?k:l+k))}f=f.next}}}}var B=[];d.forEach(function(a,c){B.push({w:c,G:a})});B.sort(function(a,c){return c.G-a.G});return B};N.prototype.C=function(a){return this.v.C(a)};p.Object.defineProperties(N.prototype,{size:{configurable:!0,enumerable:!0,get:function(){return this.l.size}}});
var Q={skis:"ski",idly:"idl",ugly:"ugli",only:"onli",news:"news",howe:"howe",bias:"bias"},R={skies:"sky",dying:"die",lying:"lie",tying:"tie",early:"earli",atlas:"atlas",andes:"andes"},S={gently:"gentl",singly:"singl",cosmos:"cosmos"},da={},T=/[^aeiouy]*[aeiouy]+[^aeiouy](\w*)/,ea=/^[aeiouy][^aeiouy]$/,fa=/.*[^aeiouy][aeiouy][^aeiouywxY]$/;function U(a){return 2===a.length?ea.test(a):fa.test(a)}var ga=/([aeiouy])y/g,ha=/[aeiouy]./,ia=/(ed|edly|ing|ingly)$/,ja=/[aeiouy]/;
function ka(a,d){if(a.endsWith("eedly"))return a.length-5>=d?a.slice(0,-3):a;if(a.endsWith("eed"))return a.length-3>=d?a.slice(0,-1):a;var b=ia.exec(a);return b&&(b=a.slice(0,-b[0].length),1<a.length&&ja.test(b))?(b.endsWith("at")||b.endsWith("bl")||b.endsWith("iz")?d=b+"e":(a=b.charCodeAt(b.length-1),d=a!==b.charCodeAt(b.length-2)||98!==a&&100!==a&&102!==a&&103!==a&&109!==a&&110!==a&&112!==a&&114!==a&&116!==a?d===b.length&&U(b)?b+"e":b:b.slice(0,-1)),d):a}
var V=[["enci","ence",null],["anci","ance",null],["abli","able",null],["izer","ize",null],["ator","ate",null],["alli","al",null],["bli","ble",null],["ogi","og",["l"]],["li","","cdeghkmnrt".split("")]],la=[["ization","ize",null],["ational","ate",null],["fulness","ful",null],["ousness","ous",null],["iveness","ive",null],["tional","tion",null],["biliti","ble",null],["lessli","less",null],["entli","ent",null],["ation","ate",null],["alism","al",null],["aliti","al",null],["ousli","ous",null],["iviti","ive",
null],["fulli","ful",null]].concat(V),W=[{c:"ational",b:"ate",f:!1},{c:"tional",b:"tion",f:!1},{c:"alize",b:"al",f:!1},{c:"icate",b:"ic",f:!1},{c:"iciti",b:"ic",f:!1},{c:"ative",b:"",f:!0},{c:"ical",b:"ic",f:!1},{c:"ness",b:"",f:!1},{c:"ful",b:"",f:!1}],X="al ance ence er ic able ible ant ement ment ent ism ate iti ous ive ize".split(" "),ma=/Y/g;
function na(a){if(3>a.length)return a;39===a.charCodeAt(0)&&(a=a.slice(1));if("sky"===a)return a;if(7>a.length)if(4===a.length){if(Q.hasOwnProperty(a))return Q[a]}else if(5===a.length){if(R.hasOwnProperty(a))return R[a]}else if(6===a.length&&S.hasOwnProperty(a))return S[a];121===a.charCodeAt(0)&&(a="Y"+a.slice(1));a=a.replace(ga,"$1Y");var d,b;b=4<a.length&&(a.startsWith("gener")||a.startsWith("arsen"))?5:a.startsWith("commun")?6:(d=T.exec(a))?a.length-d[1].length:a.length;d=(d=T.exec(a.slice(b)))?
a.length-d[1].length:a.length;39===a.charCodeAt(a.length-1)?a=a.endsWith("'s'")?a.slice(0,-3):a.slice(0,-1):a.endsWith("'s")&&(a=a.slice(0,-2));if(a.endsWith("sses"))a=a.slice(0,-4)+"ss";else if(a.endsWith("ied")||a.endsWith("ies"))a=a.slice(0,-3)+(4<a.length?"i":"ie");else if(!a.endsWith("us")&&!a.endsWith("ss")&&115===a.charCodeAt(a.length-1)){var c=a.slice(0,-1);ha.test(c)&&(a=c)}if((6===a.length||7===a.length)&&da.hasOwnProperty(a))return a;a=ka(a,b);2<a.length&&(c=a.charCodeAt(a.length-1),121===
c||89===c)&&(c=a.charCodeAt(a.length-2),97>c||121<c||97!==c&&101!==c&&105!==c&&111!==c&&117!==c&&121!==c)&&(a=a.slice(0,-1)+"i");a:for(var c=6<a.length?la:V,e=0;e<c.length;e++){var g=c[e],f;b:{var h=g[0];f=g[1];g=g[2];if(a.endsWith(h)){if(a.length-h.length>=b){h=a.slice(0,-h.length);if(null===g){f=h+f;break b}for(var k=0;k<g.length;k++)if(h.endsWith(g[k])){f=h+f;break b}}f=a}else f=null}if(null!==f){a=f;break a}}a:for(c=0;c<W.length;c++)if(e=W[c],f=e.c,e=a.endsWith(f)?a.length-f.length>=b&&(!e.f||
a.length-f.length>=d)?a.slice(0,-f.length)+e.b:a:null,null!==e){a=e;break a}a:{for(c=0;c<X.length;c++)if(e=X[c],a.endsWith(e)){a=a.length-e.length>=d?a.slice(0,-e.length):a;break a}a.length-3>=d&&(c=a.charCodeAt(a.length-4),115!==c&&116!==c||!a.endsWith("ion")||(a=a.slice(0,-3)))}c=a.charCodeAt(a.length-1);108===c?a.length-1>=d&&108===a.charCodeAt(a.length-2)&&(a=a.slice(0,-1)):101===c&&(a.length-1>=d?a=a.slice(0,-1):a.length-1>=b&&!U(a.slice(0,-1))&&(a=a.slice(0,-1)));return a=a.replace(ma,"y")}
postMessage(1);function oa(){return new Promise(function(a,d){var b=new XMLHttpRequest;b.onload=function(){var c=[];JSON.parse(b.responseText).forEach(function(a){c.push(a)});a(c)};b.onerror=function(a){d(a.message)};b.open("GET","reddit_comments.json");b.send()})}var P=new N;P.A=function(a){return na(a.toLowerCase().replace(/^\W+/,"").replace(/\W+$/,""))};O("author");O("body");var Y=!1;
onmessage=function(a){if(Y&&(a=a.data,1===a.type)){var d=P.search(a.payload);postMessage({id:a.id,type:1,payload:d.slice(0,50).map(function(a){return{docId:a.w,score:a.G}})})}};var Z;
(new Promise(function(a,d){var b=indexedDB.open("docs",1);b.onerror=function(a){d(a.message)};b.onsuccess=function(c){a(c.target.result)};b.onupgradeneeded=function(a){a=a.target.result;a.objectStoreNames.contains("comments")||a.createObjectStore("comments",{autoIncrement:!0})}})).then(function(a){Z=a;return new Promise(function(d,b){var c=a.transaction("comments").objectStore("comments").count();c.onerror=function(a){b(a.message)};c.onsuccess=function(){d(c.result)}})}).then(function(a){return 0===
a?(postMessage(2),oa().then(function(a){return new Promise(function(b,c){postMessage(3);var d=Z.transaction("comments","readwrite");d.onerror=function(a){c(a.message)};d.oncomplete=function(){b()};var g=d.objectStore("comments");a.forEach(function(a){g.add(a)})})})):Promise.resolve()}).then(function(){return new Promise(function(a,d){postMessage(4);var b=Z.transaction("comments");b.onerror=function(a){d(a.message)};b.oncomplete=function(){a()};b.objectStore("comments").openCursor().onsuccess=function(a){if(a=
a.target.result)P.add(a.key,a.value),a.continue()}})}).then(function(){postMessage(5);Y=!0});}).call(this);
